name: Scrape Notices

on:
  schedule:
    - cron: '*/5 * * * *'  # This runs every 5 minutes
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  scrape-notices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Get Latest Vercel Deployment URL
        run: |
          DEPLOYMENT_URL=$(curl -s https://api.vercel.com/v12/now/deployments?teamId=your-team-id&projectId=your-project-id | jq -r '.deployments[0].url')
          echo "Deployment URL: $DEPLOYMENT_URL"
          echo "VERCEL_URL=$DEPLOYMENT_URL" >> $GITHUB_ENV

      - name: Call Vercel Scraping API
        run: |
          echo "Calling Vercel Scraping API at $VERCEL_URL/api/scrape"
          curl -X GET https://$VERCEL_URL/api/scrape
