name: Scrape Notices

on:
  schedule:
    - cron: '*/5 * * * *'  # This runs every 5 minutes
  workflow_dispatch:  # Allows you to trigger the workflow manually
  push:
    branches:
      - server

jobs:
  scrape-notices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install mongodb puppeteer-core @sparticuz/chromium

      - name: Run Scrape Script
        run: |
          node api/scrape.js
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}  # MongoDB URI stored in GitHub Secrets
