name: Scrape Notices

on:
  schedule:
    - cron: '*/5 * * * *'  # This runs every 5 minutes
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  scrape-notices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Get Vercel Deployment URL
        id: vercel
        run: |
          echo "Vercel URL: $VERCEL_URL"
          echo "VERCEL_URL=$VERCEL_URL" >> $GITHUB_ENV

      - name: Call Vercel Scraping API
        run: |
          curl -X GET ${{ env.VERCEL_URL }}/api/scrape
