name: Scrape Notices

on:
  schedule:
    - cron: '*/5 * * * *'  # This runs every 5 minutes
  workflow_dispatch:  # Allows you to trigger the workflow manually
  push:
    branches:
        - server

jobs:
  scrape-notices:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Call Vercel Scraping API
        run: |
          echo "Calling Vercel Scraping API at https://studyhub-sepia.vercel.app/api/scrape"
          curl -X GET "https://studyhub-sepia.vercel.app/api/scrape"
